language: node_js
node_js:
  - '0.11'
env:
  - NODE_ENV=travis
deploy:
  provider: npm
  api_key:
    secure: caiz3hBJotU644WfUyPyWZPXGPbIyGNiZnRiVNRbAWEH7mY/0ZXrntxnowFT9eduPK5doFSQUsruLgTK0bvvDRn+gRSrRtjCFgadcWmUNjGUrFTA34jiBBDDIKQu29V29qqptC7Wg6jfOkOdH4fpvrDTEe8qe8EGSGZHLJ/pnpM=
  email: jffelsinger@gmail.com
  on:
    tags: true
    repo: jfelsinger/measurement
    all_branches: true
before_install:
  - npm install -g gulp mocha
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'measurement' ]; then cd .. && eval "mv $currentfolder
    measurement" && cd generator-venm; fi
script: gulp test
